//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ebayLoginAndCheck.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1M18lhUZc_6lZsuJggKiK-na9AA3pXJU_e-NQhUbLJ9Q")]
        public string GoogleSpreadsheetAPIGologin {
            get {
                return ((string)(this["GoogleSpreadsheetAPIGologin"]));
            }
            set {
                this["GoogleSpreadsheetAPIGologin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("chucnguyen1605@probable-goods-364903.iam.gserviceaccount.com")]
        public string GoogleServiceAccountAPIGologin {
            get {
                return ((string)(this["GoogleServiceAccountAPIGologin"]));
            }
            set {
                this["GoogleServiceAccountAPIGologin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\n  \"type\": \"service_account\",\n  \"project_id\": \"probable-goods-364903\",\n  \"privat" +
            "e_key_id\": \"bcea2e4cac3c020a3e79f40d4d0d3253065475ce\",\n  \"private_key\": \"-----BE" +
            "GIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDp4M61Ty" +
            "GiC+rd\\np/oC3G4uy3Hvqcz/MHh7N/+TY7/L5YAPLB1QY4R3FIgFSsYteoRaQin0e8V+INOO\\n6rT3dV" +
            "ExwhItifHNbjIMFLt4sosUcEhPobZE50sMruRT6NzysONGhft+RWDwNNgS\\nl7e34j/bJIv27RwGA+GM" +
            "3W852GIl/1xZyeAxA8ConMnqRXZQT6eDsFNmKF0caZm/\\nyiDdmPEFitjSPo0+8ewJkZ9nJwoq5pbvLL" +
            "HX7JxWfxRDTLKG3GFGAvW2EfchCNBl\\nPFwdcJIVSJCBPy5y8wkGaYMHcFugmmErD11ji3tf8blj9Om8" +
            "EMLy8oOKpikdsnAX\\n1ItZQv2HAgMBAAECggEAAkJxl3nXaC03odhCHO32mI15oShMT+OEKSNDh6/X21" +
            "yb\\nw0nDUhKsEHR1KKFDeeQBoazwTSmMS77THGyIaWL2RltKzqrTAw+UpzOPaMfyJQqS\\nqvDz2wWQXu" +
            "PVATnc4fFd42wJn9DZchNTSmwHJ90lOHT0GeN046/86V39pEWYE9Li\\nM0PCbGYrc+V6Csg1cyugFkdj" +
            "hp4V4Wq7wMheNegRIgstf20zuFD/4mkcTAoBORza\\nPC5PhDnpWYFLoWiXIUHM375xJuVDpjFQBkpcev" +
            "7VpzNARFieTb6VJ+R0AX8uDk7R\\nCpI+GWFmMN6PZOj0H3haWCwWonKOG+sWS9X4dGzoXQKBgQD22o8G" +
            "OqTCF5BSnMZh\\nonu/bEdVnS06XnRh7yMyWedgHcpMMa0WWAPt4ly6q4OgpgBBC4DHXfcYDd6p+IaZ\\n" +
            "4MuAfIgP2PWyx+ByU3r/Gysj+D3Iew0b4UNiVuUQe89LbBT39S0wZUZKEQgDkRQv\\nkWKtoYA5aMzv7r" +
            "VO2+ngak3eTQKBgQDyiyxsDxBqJ9HurHoRW8nUUZL8B86pYOs+\\nWFGfoQd3qHxWeVYJuqK1aZWCOKcD" +
            "LfDoxxTS4FkD8mGOdp7LayGasAPeYdPgTBmo\\nJwczWtLyyGBgAhBi4abuZQL47wQZgmdZsIvaQrw8Lw" +
            "FS2HcNa2FnyeSFFKGsoHSE\\ny2ihNFp9IwKBgQCAre/OjHVkZAostmLHdH7Ti2soGvX/rks23gTX83uk" +
            "ZAMXcvHK\\navkpYU17VXsZHE+XmJp50ubCmEBRFCd+QWtzv/bhY/S4TG8YyaGdKBl196qlPlfY\\nB7Yr" +
            "piZkUFX/+Ah6NUloJ/LbG0O1MER4g24QGtcPliz2idXjlMm23VNYJQKBgCZo\\nV459DDJjP+E1utbI3D" +
            "sc99OlQNqdmGL1BWfrzgzqx1XCPRepUF6964kFg50DR2T1\\nMZz7Hd18Imq26gp4WofuW455m12nb2Cr" +
            "XX6KYWFEzc4mRYYDCbYylLfq0ZFgjxEq\\n3dqgOsKlBuahlKixWmlfFSrly3xUpF7q/xSX/8RVAoGALL" +
            "JahLlpxbcdaNLikFMk\\n9PG+CtYUHhGuS+UcqkWJCj6uautnvUBDppkTdAs5uYCp6GsEBY9G4faUUkmQ" +
            "bxRh\\nPuVarLOpLSZt6xCvqXP6z4UNgNpARshReLBAjmeuLDsN+L/cjKYtDyOpNJAQLMAW\\n/7s+mQG1" +
            "yQDSdOpQgIZIjYM=\\n-----END PRIVATE KEY-----\\n\",\n  \"client_email\": \"chucnguyen160" +
            "5@probable-goods-364903.iam.gserviceaccount.com\",\n  \"client_id\": \"10179516280772" +
            "8252559\",\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\n  \"token_ur" +
            "i\": \"https://oauth2.googleapis.com/token\",\n  \"auth_provider_x509_cert_url\": \"htt" +
            "ps://www.googleapis.com/oauth2/v1/certs\",\n  \"client_x509_cert_url\": \"https://www" +
            ".googleapis.com/robot/v1/metadata/x509/chucnguyen1605%40probable-goods-364903.ia" +
            "m.gserviceaccount.com\",\n  \"universe_domain\": \"googleapis.com\"\n}\n")]
        public string JsonCredentialAPIGologin {
            get {
                return ((string)(this["JsonCredentialAPIGologin"]));
            }
            set {
                this["JsonCredentialAPIGologin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1yyAfzAtL_11gVaKimUAZnrVgZ5IFNwI6bIlgEH0DWsM")]
        public string GoogleSpreadsheetId1 {
            get {
                return ((string)(this["GoogleSpreadsheetId1"]));
            }
            set {
                this["GoogleSpreadsheetId1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("coz2002@optical-psyche-412203.iam.gserviceaccount.com")]
        public string GoogleServiceAccountName1 {
            get {
                return ((string)(this["GoogleServiceAccountName1"]));
            }
            set {
                this["GoogleServiceAccountName1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"type\": \"service_account\",\r\n  \"project_id\": \"optical-psyche-412203\",\r\n  \"pri" +
            "vate_key_id\": \"1be4b19455ec8ebe2b367723a0968702c54b9f33\",\r\n  \"private_key\": \"---" +
            "--BEGIN PRIVATE KEY-----\\nMIIEvAIBADANBgkqhkiG9w0BAQEFAASCBKYwggSiAgEAAoIBAQCSKB" +
            "zxFhyURWrf\\n52EnfcqviQqa6/87QbWFWGVijOCMQNImLxHAmgMUX/qAMRXBbY5DcOQEmDutYsVL\\nv3" +
            "Ww/3ZWBBrIxScH+EZktNfVChmyfK8dPs/ppTG4Mp/pL2FKwNc6dvEe737z0o3Q\\npyP//wcpjlbMOUXk" +
            "d37ItwTBjPlWRF8tL7dQ1U6vWVzDGE9SumXUzt0ak4ocMHGO\\nx8o8GkDRcfZp73pfFEtlH/HmCHIZJ+" +
            "S6eOEmKhY0/LjdqIxusV0ofeK8KEcjOpq/\\nMRLzBW7b0R86u/y7ykgMqYjZVMECfw93tvt1BQoYOp+L" +
            "WSIIkqvySqetO8wZKgDZ\\nkYAc11X/AgMBAAECggEAFSU74rQUmG2z+Qbsax6WQhqCmp1a2i43M+lGac" +
            "wApL9a\\nvW7Wk6tJ7MW3Y+/guju+dwq7LTWqf1BTQ71EgBdwUyDZkIMtksfxxJosFm9qqQRv\\nABKEBB" +
            "qupyaeih8dEAf3BkdfuokN21Add7rmyMpoiojvDTGavLjTx/g/9jy4yikh\\nifdznpT+G5Blpkqa7jCU" +
            "MdpoPIuOWUH27ZOqLNcsWLygyW443Isy0LUnYK3SjvPs\\nCzufkrhaA2oZlfgVLUM9p2xzgcxUFXFagK" +
            "z3e1d8DFmNT6BF0QLXt7ejx1k5WWYU\\nVlTBJfu42Qsb9aGR7RJ+vf+azBpOd21DwOCXWwonCQKBgQDC" +
            "GNAVgkLU7J/b93tY\\nmKDzgT/U/Trh9eAvkuBWYXOU6OE5GyZkvx3FTiYsm3Wk/1k0pjFqU90Ty5WCBm" +
            "Sy\\n0jx89U806SY8FDUnNh5vQKDrUagHR0ETg2MFk92zY4z3XoL5d7+KEJhA4PgCvTGP\\nNjD7UvrH8j" +
            "JJmOOV69UTWuu0GwKBgQDAxS8yemqR3Xn6ASDSvgAljiPsIGA4NLRr\\nuDWdHRiq0BrDwAMUmKBiwkwS" +
            "Xsy1aQv+pLw9+nN5DcFB6KcUAry9204ioFEAeNjw\\njRwszQPYXhTH9wBUmTuQV1orsA3goJbWBuvEJx" +
            "qIPAWznivVWWK2QHsBseGrkMLR\\nQLkdmJRb7QKBgHyyZDztSvJwcuNmw5/PrtfCGbhEWCgDRtxJiEb2" +
            "pMLuOoPtpWTk\\nQ8QWyP+vgI1YX38rpmOhLU8iZBL8+ITJ/IJrN0/O2fmPIfbnFfZzlu6Xr1O9u1lF\\n" +
            "98AFl1FAi7gAyDRtcmjI8If+AFgCJGzVa/KLBQKf3x7ZUp1mvaWJrBQxAoGAU4ee\\nEfN1pksgBbLjdC" +
            "4chil3a2QEDZbY7yxdHv1yqOGQF25mZ1BTfzfOGs+1SI6CQg9D\\n+l9CFhxdt5+GdmdRPbt/ugVZ1CiJ" +
            "aILcyJT1q5Xoz1U6cW4Mn1kam3+oI8OyWH+b\\nPd3r40iO9+v79nDLE0oRgwR/UwZhRKcVD7wD3WkCgY" +
            "BX3BQxbEOSXOCslsCFY/JK\\nQsvkrRNNudtbFdhr0QNKDcjQPUhjwQIzQIm8AhEld8Ki4PWK+L8mKHl0" +
            "6wiNRJLc\\nROpMg5Be23oOeeIDIVckHvJQUBIpxnZYTg0SR+Ap9V5nx1xwd/nvMefv+jgybuo3\\n6HwW" +
            "Khx9LUpelSEsGHUCWQ==\\n-----END PRIVATE KEY-----\\n\",\r\n  \"client_email\": \"coz2002@" +
            "optical-psyche-412203.iam.gserviceaccount.com\",\r\n  \"client_id\": \"115048839015360" +
            "965320\",\r\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\r\n  \"token_u" +
            "ri\": \"https://oauth2.googleapis.com/token\",\r\n  \"auth_provider_x509_cert_url\": \"h" +
            "ttps://www.googleapis.com/oauth2/v1/certs\",\r\n  \"client_x509_cert_url\": \"https://" +
            "www.googleapis.com/robot/v1/metadata/x509/coz2002%40optical-psyche-412203.iam.gs" +
            "erviceaccount.com\",\r\n  \"universe_domain\": \"googleapis.com\"\r\n}")]
        public string JsonCredential1 {
            get {
                return ((string)(this["JsonCredential1"]));
            }
            set {
                this["JsonCredential1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("18uBsNVRPKheYe6RobnAwXAdbv5JyIPyaWvK4__fIsuw")]
        public string GoogleSpreadsheetId2 {
            get {
                return ((string)(this["GoogleSpreadsheetId2"]));
            }
            set {
                this["GoogleSpreadsheetId2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fairlambbrandi508@nomadic-coast-410708.iam.gserviceaccount.com")]
        public string GoogleServiceAccountName2 {
            get {
                return ((string)(this["GoogleServiceAccountName2"]));
            }
            set {
                this["GoogleServiceAccountName2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("{\r\n  \"type\": \"service_account\",\r\n  \"project_id\": \"nomadic-coast-410708\",\r\n  \"priv" +
            "ate_key_id\": \"82e84ad8bf5e79156d5e6557bf72683357fda76a\",\r\n  \"private_key\": \"----" +
            "-BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCxGEA" +
            "towo/m/BB\\n5ugY9XS3HMF3p6AZvjYQZMEX3rkmVKAZ2GB5CGP4hoGaAKY6uQXg+eiTpqnpam6k\\nj1F" +
            "T3h4qYfl4gJF9lDO7sPSfluQRUvj9mg1w9L0MK7mQarWp6Af3BBHpDRbgFhuI\\nT+JF7Kb0wSaLl6n6P" +
            "n7POfbT/nqV8VI4uc43M6qZYFK7allUbgXpSSGa41bAFnIm\\npiIb+y/MBeR/aFClyNAlIz3xmk0168w" +
            "3+O4LAK+IJqBMZtLFLP3UNHpUNi7Yybrn\\nHQSYQRBjUi3smJScUVvKDR0bEeG4JW9wmn/ghJor1bvXo" +
            "8wNJvpS6XyzhwTNjSQ8\\nmL4XedQzAgMBAAECggEACZEyUmTW9mXBvoWvbz2/bu8GQqUTIKDmgc83oUb" +
            "+gKQc\\nvBi06YT7BZ+am8vCLzT0rNlDZ8qerkX6MTiu35WF0qtVU126vmqFuvON25tGuere\\nGbE7Xal" +
            "TFze7gCJLqyCmYYFeSFVVMYjwNtZ99mIZCOrwXqU0YRkEN8S9YWmDjNsU\\nIKvGR1GU1KvUBrkSvLZzx" +
            "im7xPqeXHYFg+goea5crZwq9F8sjLrvfEuZAyh1llUM\\nXaMW6iL65mVMxGxxFH6VEBLk5AcXacDFTuO" +
            "JIhXvKrra18BF9vWoBSUWmpf23X/o\\naRMCC5/5hIoINiPv1vCeBpqCrUkX5IyCLDXnfjIbfQKBgQDXZ" +
            "yg8+TJ4o7KyBR4t\\nkXe1lMG4Z4jENOXDKM0VwtdoZKbPJ7VKpVtamUkAbu0DUwElPLPqVb7UmKq4d2o" +
            "z\\nbTTgJ9t9zMXf2UQwK2UIXNerzk6r2URzvB3sohuofmG7X81zLzXOc2x0UrTrf5S6\\n8Ds2mkgjCUK" +
            "g1DrzuLbQP+mCxwKBgQDSeMih1GlgprVZqubx9+Bn7gjOxoFEjkWL\\nrNo2sfGJS3jtm4NhHUdf1ndpY" +
            "b5Vy7uRDzFzsaZJLNuEyuKOSLNrwKszfMZbci+a\\nA7X1iPSHIe/V6CdIclKsBBuOTcLOyPDY3OTGWWO" +
            "yjhIeGMe8/l/tSALDNfFxRJlS\\noLolXa83NQKBgQCeHKCSsTD1EOQYfF08gaznYrwYCheAPnvxF0ADG" +
            "zRW8prnMHSI\\nyHwYMrA9Wy8q44DRvo8qEaq0DyQxp6YS/bR0XY1l+Cu/NpIw8YmF6/B7skJZLnBq\\nq" +
            "8kja5L1yV8f1SDPzfWnB16yvAsFWm7oEXLFj9YnsaJwv5hOUmYO0vsq/QKBgByQ\\nI7pCl2J0fVwD43+" +
            "nAh9YoH1fVx+0px+Df8G4eG0HfwvP9Q5y6MLK2j3E9A20rmnL\\nRAzNaSG5Irlsxz5EA4V2CkXcgxbZ8" +
            "jfWlRUTVwwXwPKopNwiF7IchJjVWMCzaGwl\\n3i5E51DOEwtelYzCgMY05ZsUcQXMJ3qdMWXsxuCZAoG" +
            "AQXWvSGW+m6B42ixzZKdG\\nekFYMRtewkqtTXVAQuwiMW3+Z5pv1rSjk6Dg9/tYa3nkGblelCJtvE3Hq" +
            "K6mymOf\\ni2UQy8cJHnlp1D1YpzthQqWxGWUa+yOq4Hf4RurNhWyiqazk9AUMqG23YN4GfyeL\\nUPSO8" +
            "sisbCxagTFNOWX8BkE=\\n-----END PRIVATE KEY-----\\n\",\r\n  \"client_email\": \"fairlambb" +
            "randi508@nomadic-coast-410708.iam.gserviceaccount.com\",\r\n  \"client_id\": \"1132031" +
            "44241027314946\",\r\n  \"auth_uri\": \"https://accounts.google.com/o/oauth2/auth\",\r\n  " +
            "\"token_uri\": \"https://oauth2.googleapis.com/token\",\r\n  \"auth_provider_x509_cert_" +
            "url\": \"https://www.googleapis.com/oauth2/v1/certs\",\r\n  \"client_x509_cert_url\": \"" +
            "https://www.googleapis.com/robot/v1/metadata/x509/fairlambbrandi508%40nomadic-co" +
            "ast-410708.iam.gserviceaccount.com\",\r\n  \"universe_domain\": \"googleapis.com\"\r\n}")]
        public string JsonCredential2 {
            get {
                return ((string)(this["JsonCredential2"]));
            }
            set {
                this["JsonCredential2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("EbayLoginAndCheck")]
        public string hash {
            get {
                return ((string)(this["hash"]));
            }
            set {
                this["hash"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string keyEcrypt {
            get {
                return ((string)(this["keyEcrypt"]));
            }
            set {
                this["keyEcrypt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1WHGpTlzQjNMqNWR1iitr7iRURoV0sHfnKWynO9iKeLo")]
        public string GoogleSpreadsheetIdKey {
            get {
                return ((string)(this["GoogleSpreadsheetIdKey"]));
            }
            set {
                this["GoogleSpreadsheetIdKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string keyActive {
            get {
                return ((string)(this["keyActive"]));
            }
            set {
                this["keyActive"] = value;
            }
        }
    }
}
